name: sys_idn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - _x86_64-microarch-level=3=2_skylake
  - alsa-lib=1.2.14=hb9d3cd8_0
  - ampl-asl=1.0.0=h5888daf_2
  - assimp=5.4.3=h8943939_0
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - casadi=3.7.0=py310h2866ee3_2
  - clarabel=0.11.0=py310h9d7ab16_0
  - cli11=2.5.0=h3f2d84a_0
  - coal=3.0.1=hff52083_1
  - coal-python=3.0.1=py310h81fdb92_1
  - console_bridge=1.0.2=h924138e_1
  - contourpy=1.3.2=py310h3788b33_0
  - cvxpy=1.6.5=py310hff52083_0
  - cvxpy-base=1.6.5=py310h5eaa309_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - eigen=3.4.0=h00ab1b0_0
  - eigenpy=3.10.3=np20py310h3ff4570_0
  - elfutils=0.191=h924a536_0
  - expat=2.7.0=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py310h89163eb_0
  - freetype=2.13.3=ha770c72_1
  - gdbm=1.18=h0a1914f_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h86084c0_1
  - graphite2=1.3.13=h59595ed_1003
  - harfbuzz=10.4.0=h76408a6_0
  - hpp-fcl=3.0.1=pyhd3e5650_1
  - icu=75.1=he02047a_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipopt=3.14.17=h7fd866c_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=hadbb8c3_0
  - libasprintf=0.24.1=h8e693c7_0
  - libblas=3.9.0=20_linux64_mkl
  - libblasfeo=0.1.4.2=had105d5_300
  - libboost=1.86.0=hb8260a3_2
  - libboost-devel=1.86.0=h1a2810e_2
  - libboost-headers=1.86.0=ha770c72_2
  - libboost-python=1.86.0=py310ha2bacc8_2
  - libboost-python-devel=1.86.0=py310hb7f781d_2
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=20_linux64_mkl
  - libclang-cpp19.1=19.1.7=default_hb5137d0_3
  - libclang13=19.1.7=default_h9c6a7e4_3
  - libcoal=3.0.1=ha55d5d9_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libfatrop=0.0.4=h5888daf_1
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgettextpo=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgz-cmake3=3.5.3=hac33072_0
  - libgz-math7=7.5.1=h5888daf_2
  - libgz-tools2=2.0.1=h17585e0_0
  - libgz-utils2=2.2.0=h5888daf_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=20_linux64_mkl
  - libllvm19=19.1.7=ha7bfdaf_1
  - libmicrohttpd=1.0.1=hbc5bc17_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libosqp=0.6.3=h5888daf_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - libqdldl=0.1.7=hcb278e6_0
  - libscotch=7.0.5=h3428b0d_3
  - libsdformat14=14.5.0=hea37092_2
  - libspral=2025.03.06=h39c1cf3_0
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.7.0=he137b08_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=hb346dea_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.5=h024ca30_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - matplotlib=3.10.3=py310hff52083_0
  - matplotlib-base=3.10.3=py310h68603db_0
  - metis=5.1.0=hd0bcaf9_1007
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mumps-include=5.7.3=ha770c72_5
  - mumps-seq=5.7.3=hcd84eb1_5
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.4=h6a678d5_0
  - nettle=3.10.1=h4a9d5aa_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - octomap=1.10.0=h84d6215_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.0=h7b32b05_1
  - osqp=0.6.7.post3=py310h5eaa309_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=hc749103_2
  - pillow=11.2.1=py310h7e6dc6c_0
  - pinocchio=3.7.0=py310hb04e4ba_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.0=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.8.2=py310hfd10a26_0
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=7_cp310
  - pyyaml=6.0.2=py310h89163eb_2
  - qdldl-python=0.1.7.post5=np20py310h5ebf739_1
  - qhull=2020.2=h434a139_5
  - qhull-static=2020.2=h434a139_5
  - qt6-main=6.8.2=h588cce1_0
  - readline=8.2=h5eee18b_0
  - ruby=3.2.2=h983345b_1
  - scipy=1.15.2=py310h1d65ade_0
  - scs=3.2.7.post2=default_py310he39ec6d_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.32.3=hcee41ef_1
  - tbb=2021.8.0=hdb19cb5_0
  - tinyxml2=11.0.0=h3f2d84a_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.5.1=py310ha75aee5_0
  - trimesh=4.6.10=pyh7b2049a_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - urdfdom=4.0.1=hae71d53_3
  - urdfdom_headers=1.1.2=h84d6215_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cython==3.1.1
      - future-fstrings==1.2.0
      - lxml==5.4.0
      - mosek==10.0.46
      - urdf-parser-py==0.0.4
prefix: /home/khorshidi/miniconda3/envs/sys_idn